title: Dokyun Lee
description: Ph.D Student
site_title: 'Dokyun Lee'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: dokyunlee
blog_url: https://www.nagekar.com
email: dno04114@gmail.com
keybase_username: abhn
twitter_username: abhn_
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/dk.jpg

# Google Analytics ID
google_analytics: 
